export const jobsData = [
  {
    title: 'Sales Intern',
    type: 'Full-Time, Intenship',
    location: 'On-Site',
    pdfUrl: '/job/sales-intern-new.pdf',
  },
  {
    title: 'Admin Intern',
    type: 'Full-Time, Internship',
    location: 'On-Site',
    pdfUrl: '/job/admin-intern-new.pdf',
  },
  {
    title: 'Backoffice Assistant',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/backoffice-assistant.pdf',
  },
  {
    title: 'Procurement Specialist',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/procurement-specialist-g-rollz.pdf',
  },
  {
    title: 'Supply Chain Planner',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/supply-chain-planner.pdf',
  },
  {
    title: 'Warehouse Manager',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/warehouse-manager.pdf',
  },
  {
    title: 'Supply Chain Analyst Intern',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/supply-chain-intern.pdf',
  },
  {
    title: 'Sales Intern',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/sales-intern.pdf',
  },
  {
    title: 'Procurement Specialist',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/procurement-specialist.pdf',
  },
  {
    title: 'Head of Operations',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/head-of-operations.pdf',
  },
  {
    title: 'IT Manager',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/it-manager.pdf',
  },
  {
    title: 'Backoffice Intern',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/backoffice-intern.pdf',
  },
  {
    title: 'Admin Intern',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/admin-intern.pdf',
  },
  {
    title: 'IT Support Intern',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/it-support-intern.pdf',
  },
  {
    title: 'Oracle ERP Consultant / Specialist',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/oracle-functional-consultant.pdf',
  },
  {
    title: 'SEO Specialist',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/seo-specialist.pdf',
  },
  {
    title: 'Finance Specialist',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/finance-specialist.pdf',
  },
  {
    title: 'Marketing Manager',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/digital-marketing-manager.pdf',
  },
  {
    title: 'Content Writer (5+ yrs)',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/content-writer5.pdf',
  },
  {
    title: 'ML Engineer',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/ml-eng-of.pdf',
  },
  {
    title: 'Data Engineer',
    type: 'Full-Time, Contract',
    location: 'On-Site',
    pdfUrl: '/job/data-engineer.pdf',
  },
  {
    title: 'IT Specialist',
    type: 'Full-Time',
    location: 'On-Site',
    pdfUrl: '/job/it-specialist.pdf',
  },
];
